ignore_merge_commits = true
branch_whitelist = ["master", "release/*"]
pre_bump_hooks = []
post_bump_hooks = []
tag_prefix = "v"

[commit_types]

[changelog]
path = "CHANGELOG.md"
authors = []

[bump_profiles]
