name: Update

on: 
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - composer.lock

jobs:
  update-satis:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke Satis Update
        uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: buckhamduffy
          repo: composer
          github_token: ${{ secrets.AARON_ACCESS_TOKEN }}
          workflow_file_name: satis.yml
          ref: master
          wait_workflow: false